GRANT CONNECT ON DATABASE {dbname} TO metabasepostgre;
GRANT USAGE ON SCHEMA company TO metabasepostgre;
GRANT SELECT ON ALL TABLES IN SCHEMA company TO metabasepostgre;
GRANT SELECT ON ALL TABLES IN SCHEMA fundamental TO metabasepostgre;
GRANT SELECT ON ALL TABLES IN SCHEMA stocks TO metabasepostgre;
GRANT SELECT ON ALL TABLES IN SCHEMA eps TO metabasepostgre;

ALTER DEFAULT PRIVILEGES IN SCHEMA company GRANT SELECT ON TABLES TO metabasepostgre;
ALTER DEFAULT PRIVILEGES IN SCHEMA fundamental GRANT SELECT ON TABLES TO metabasepostgre;
ALTER DEFAULT PRIVILEGES IN SCHEMA stocks GRANT SELECT ON TABLES TO metabasepostgre;
ALTER DEFAULT PRIVILEGES IN SCHEMA eps GRANT SELECT ON TABLES TO metabasepostgre;
